#!/bin/sh

ERRFILE=$XDG_CACHE_HOME/X11/xsession-errors

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/Xresources
sysmodmap=/etc/X11/xinit/Xmodmap

# merge in defaults and keymaps
if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi



# start some nice programs

setxkbmap -option caps:escape &
zsh -c ~/dotfiles/scripts/screenlayout.sh &
nitrogen --restore &
dunst &
pulseaudio &
exec xmonad

