#!/bin/sh

ERRFILE=$XDG_CACHE_HOME/X11/xsession-errors

userresources=$XDG_CONFIG_HOME/X11/xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/Xresources
sysmodmap=/etc/X11/xinit/Xmodmap

# merge in defaults and keymaps
if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi



xhost +local:

# start some nice programs

# for xmonad
trayer-srg --edge top --align right --SetDockType true --SetPartialStrut true --expand true --width 10 --tint 0x101010 --height 43 --transparent true --alpha 0 --monitor primary &

nm-applet &
cbatticon &
xsetroot -cursor_name left_ptr
setxkbmap -option caps:escape &
zsh -c ~/dotfiles/scripts/screenlayout.sh &
nitrogen --restore &
dunst &
pulseaudio &
pasystray -g -m 100 &
exec dbus-launch --exit-with-session xmonad

#nscde
# exec dbus-launch --exit-with-session nscde
