#!/bin/sh

ERRFILE=$XDG_CACHE_HOME/X11/xsession-errors

userresources=$XDG_CONFIG_HOME/X11/xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/Xresources
sysmodmap=/etc/X11/xinit/Xmodmap

xsetroot -cursor_name left_ptr &
zsh -c ~/dotfiles/scripts/screenlayout.sh &

# merge in defaults and keymaps
if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi




# start some nice programs

xhost +local:
xset r rate 400 25
# for xmonad
trayer --edge top --align right --SetDockType true --SetPartialStrut true --expand true --width 20 --tint 0x222222 --height 30 --transparent true --alpha 0 --monitor primary &

# ibus-daemon -rxRd &
nm-applet &
cbatticon &
dunst &
#birdtray &
pasystray -g -m 100 &
setxkbmap -option caps:escape &
zsh -c ~/dotfiles/scripts/fehbg.sh &
xinput set-prop 12 335 0 &
easyeffects -w &
exec dbus-launch --exit-with-session xmonad

