[font]
size = 15.0

[font.bold]
family = "Terminess Nerd Font"
style = "Bold"

[font.bold_italic]
family = "Terminess Nerd Font"
style = "Bold Italic"

[font.italic]
family = "Terminess Nerd Font"
style = "Italic"

[font.normal]
family = "Terminess Nerd Font"
style = "Regular"

[window]
opacity = 0.97
